name: face_camera_example
description: Demonstrates how to use the face_camera plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  face_camera:
    # When depending on this package from a real application you should use:
    #   face_camera: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  talker_flutter: ^3.1.9
  talker_dio_logger: ^2.2.3
  device_preview: ^1.1.0
  permission_handler: ^10.4.3
  talker_bloc_logger: ^2.2.0
  get_it: ^7.6.0
  open_file: ^3.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  image: ^4.0.17
  go_router: ^10.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  fluttericon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icon/

  fonts:
    - family: 'Inter'
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: Workspace
      fonts:
        - asset: assets/fonts/Workspace.ttf
    - family: workspace_second
      fonts:
        - asset: assets/fonts/workspace_second.ttf